import { Geist, Geist_Mono } from "next/font/google";
import { checkDevice } from "../../lib/device";

import './common2.css';

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }) {
  // Lấy headers từ server
  const {device, userAgent } = await checkDevice()
  return (
    <html lang="en-us" className={device} data-useragent={userAgent} >
      <body>
        {children}
      </body>
    </html>
  );
}

